cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4/minecraft/mods
cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4.agent0/minecraft/mods
cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4.agent1/minecraft/mods
cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4.agent2/minecraft/mods
cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4.agent3/minecraft/mods
cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4.agent4/minecraft/mods
cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4.agent5/minecraft/mods
cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4.agent6/minecraft/mods
cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4.agent7/minecraft/mods
cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4.agent8/minecraft/mods
cp /home/toast/projects/mech_interp/homunculus/build/libs/homunculus-0.1.0.jar /home/toast/.local/share/PrismLauncher/instances/1.21.4.agent9/minecraft/mods
